theme = "solarized-light"
icons = "awesome5"


[[block]]
block = "networkmanager"
on_click = "nm-connection-editor"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []


[[block]]
block = "disk_space"
path = "/"
alias = "/"
format = "{used} used {available} free"


[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
driver = "upower"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}/{mem_total;G}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}%"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d.%m %T"
